# Generated by Django 5.2.10 on 2026-01-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date de début de la prescription (format YYYY-MM-DD)')),
                ('end_date', models.DateField(help_text='Date de fin de la prescription (format YYYY-MM-DD)')),
                ('status', models.CharField(choices=[('valide', 'valide'), ('en_attente', 'en_attente'), ('suppr', 'suppr')], default='valide', help_text='Statut de la prescription', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='Commentaire libre sur la prescription', null=True)),
                ('medication', models.ForeignKey(help_text='Médicament prescrit', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.medication')),
                ('patient', models.ForeignKey(help_text='Patient associé à cette prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-start_date', 'patient', 'id'],
            },
        ),
    ]
